DROP DATABASE ProgettoIDS;
CREATE DATABASE ProgettoIDS;
USE ProgettoIDS;

CREATE TABLE User(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,
    username VARCHAR(30) NOT NULL UNIQUE,
	fiscalCode VARCHAR(20) UNIQUE NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL
);

CREATE TABLE Participation(
    PRIMARY KEY (userId, cityId, roleId),
	userId INTEGER NOT NULL REFERENCES User.id,
	cityId INTEGER NOT NULL REFERENCES City.id,
	roleId INTEGER NOT NULL REFERENCES Role.id
);

CREATE TABLE City(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	cadastralCode VARCHAR(4) UNIQUE,
	name VARCHAR(30) NOT NULL,
	region VARCHAR(30) NOT NULL,
	province VARCHAR(30) NOT NULL,
	istatCode INTEGER UNIQUE,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL
);

CREATE TABLE Point(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	description VARCHAR(120),
	longitude FLOAT NULL,
	latitude FLOAT NULL,
	altitude FLOAT NULL,
	imageUrl VARCHAR(80),
	cityId INTEGER NOT NULL REFERENCES City.id
);

CREATE TABLE Contest(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	description VARCHAR(120),
	publicationDate DATETIME NOT NULL,
	closingDate DATETIME NOT NULL,
	animatorId INTEGER NOT NULL REFERENCES User.id,
	cityId INTEGER NOT NULL REFERENCES City.id ,
	winnerId INTEGER REFERENCES User.id
);

CREATE TABLE Content(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	description VARCHAR(120) NOT NULL,
	publicationDate DATETIME NOT NULL,
    status ENUM('Pending', 'Published', 'Rejected', 'Draft') NOT NULL,
    authorId INTEGER NOT NULL REFERENCES User.id,
	pointId INTEGER NOT NULL REFERENCES Point.id,
	mediaId INTEGER REFERENCES Media.id,
	contestId INTEGER REFERENCES Contest.id
);

CREATE TABLE Media(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	path VARCHAR(50) NOT NULL
);

CREATE TABLE Role(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL UNIQUE,
	description VARCHAR(80) NOT NULL
);
/*
CREATE TABLE SystemProblemReport(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	description VARCHAR(120),
	date DATETIME NOT NULL,
	version VARCHAR(20) NOT NULL,
	instructions VARCHAR(120) NOT NULL,
	userId INTEGER NOT NULL REFERENCES User.id
);

CREATE TABLE ContentReport(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(30) NOT NULL,
	date DATETIME NOT NULL,
	userId INTEGER NOT NULL REFERENCES User.id,
	contentId INTEGER NOT NULL REFERENCES Content.id
);

CREATE TABLE RoleChangeRequest(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(30) NOT NULL,
	date DATETIME NOT NULL,
	userId INTEGER NOT NULL REFERENCES User.id,
	requiredRoleId INTEGER NOT NULL REFERENCES Role.id,
	cityId INTEGER NOT NULL REFERENCES City.id ,
	status ENUM('Pending', 'Accepted', 'Rejected') NOT NULL
);
 */