CREATE TABLE User(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,
	fiscalCode VARCHAR(16) UNIQUE NOT NULL,
	email VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR(30) NOT NULL
);

CREATE TABLE Participation(
	userId INTEGER NOT NULL REFERENCES User.id,
	cityId INTEGER NOT NULL REFERENCES City.id,
	roleId INTEGER NOT NULL REFERENCES Role.id
);

CREATE TABLE City(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	cadastralCode VARCHAR(4) UNIQUE,
	name VARCHAR(30) NOT NULL,
	region VARCHAR(30) NOT NULL,
	province VARCHAR(30) NOT NULL,
	istatCode INTEGER UNIQUE
);

CREATE TABLE Point(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	description VARCHAR(30),
	longitude FLOAT NOT NULL,
	latitude FLOAT NOT NULL,
	altitude FLOAT NOT NULL,
	imagePath VARCHAR(50),
	cityId INTEGER NOT NULL REFERENCES City.id
);

CREATE TABLE Contest(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	description VARCHAR(30),
	publicationDate DATETIME NOT NULL,
	closingDate DATETIME NOT NULL,
	animatorId INTEGER NOT NULL REFERENCES User.id,
	cityId INTEGER NOT NULL REFERENCES City.id ,
	winnerId INTEGER REFERENCES User.id
);

CREATE TABLE Content(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	description VARCHAR(30) NOT NULL,
	date DATETIME NOT NULL,
	pointId INTEGER NOT NULL REFERENCES Point.id,
	statusId INTEGER NOT NULL REFERENCES ContentStatus.id,
	mediaId INTEGER REFERENCES Media.id,
	contestId INTEGER REFERENCES Contest.id
);

CREATE TABLE Media(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	path VARCHAR(50) NOT NULL
);

CREATE TABLE Role(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL UNIQUE,
	description VARCHAR(30) NOT NULL
);

CREATE TABLE ContentStatus(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE SystemProblemReport(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	description VARCHAR(30),
	date DATETIME NOT NULL,
	version VARCHAR(30) NOT NULL,
	instructions VARCHAR(100) NOT NULL,
	userId INTEGER NOT NULL REFERENCES User.id
);

CREATE TABLE ContenReport(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(30) NOT NULL,
	date DATETIME NOT NULL,
	userId INTEGER NOT NULL REFERENCES User.id,
	contentId INTEGER NOT NULL REFERENCES Content.id
);

CREATE TABLE RoleChangeRequest(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(30) NOT NULL,
	date DATETIME NOT NULL,
	userId INTEGER NOT NULL REFERENCES User.id,
	requiredRoleId INTEGER NOT NULL REFERENCES Role.id,
	cityId INTEGER NOT NULL REFERENCES City.id ,
	statusId INTEGER NOT NULL REFERENCES RequestStatus.id
);

CREATE TABLE RequestStatus(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	type VARCHAR(30) NOT NULL
);